# -*- coding: utf-8 -*-
"""AI_assignment_1_dijsktras_algorithm_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFavak8T1j-NzqEKGernvCRLeGIij1Tt
"""

from google.colab import files

uploaded = files.upload()

"""Check the dataset"""

import pandas as pd

df = pd.read_csv("indian-cities-dataset.csv")

print(df.head())
print(df.shape)
print(df.columns)

print("Rows:", len(df))
print("Unique cities:", len(set(df["Origin"]) | set(df["Destination"])))

print("\nCities:")
print(sorted(set(df["Origin"]) | set(df["Destination"])))

"""graph from dataset"""

from collections import defaultdict

class Graph:
    def __init__(self):
        self.adj = defaultdict(dict)

    def add_edge(self, u, v, distance):
        self.adj[u][v] = distance
        self.adj[v][u] = distance

    def resolve(self, name):
        lookup = {city.lower(): city for city in self.adj}

        if name.lower() in lookup:
            return lookup[name.lower()]

        raise KeyError(f"City '{name}' not found.")

"""Building  the Indian-city graph from data"""

graph = Graph()

for _, row in df.iterrows():
    origin = row["Origin"]
    destination = row["Destination"]
    distance = float(row["Distance"])

    graph.add_edge(origin, destination, distance)

print("Number of cities:", len(graph.adj))

"""implementation Dijkstra"""

from heapq import heappush, heappop
from math import inf

def dijkstra(graph, source, target=None):

    dist = {source: 0}
    parent = {source: None}

    heap = [(0, source)]
    visited = set()

    while heap:

        current_distance, current_city = heappop(heap)

        if current_city in visited:
            continue

        visited.add(current_city)

        if current_city == target:
            break

        for neighbor, road_distance in graph.adj[current_city].items():

            new_distance = current_distance + road_distance

            if new_distance < dist.get(neighbor, inf):

                dist[neighbor] = new_distance
                parent[neighbor] = current_city

                heappush(heap, (new_distance, neighbor))

    return dist, parent

"""the path function"""

def build_path(parent, city):

    path = []

    while city is not None:
        path.append(city)
        city = parent[city]

    return path[::-1]

source = input("Enter source city: ")
destination = input("Enter destination city: ")

# Remove extra spaces
source = source.strip()
destination = destination.strip()

try:
    source = graph.resolve(source)
    destination = graph.resolve(destination)

    dist, parent = dijkstra(graph, source, destination)

    if destination in dist:
        path = build_path(parent, destination)

        print("\nShortest Path:")
        print(" -> ".join(path))

        print("\nTotal Distance:")
        print(f"{dist[destination]:.0f} km")

    else:
        print(f"\nNo route found from {source} to {destination}.")

except KeyError as e:
    print("\nError:", e)

