# -*- coding: utf-8 -*-
"""AI_assignment_3q_uav.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8qx4wl75sjcO8UNw67F6q73ovjBzyWD

3. In the above problem, we relax the condition that all obstacles are Static. In a real world,
obstacles can be dynamic and not known a priori. How do you make the UGV navigate and
find the optinal path in a dynamic obstacles environment.

Import libraries
"""

import random
import time
import heapq
from math import inf, sqrt
import matplotlib.pyplot as plt

"""Problem parameters"""

SIZE = 70
START = (0, 0)
GOAL = (69, 69)
DENSITY = 0.25
NUM_DYNAMIC = 25
P_MOVE = 0.5
SENSOR_RADIUS = 5
SEED = 3
print("Battlefield:", SIZE, "x", SIZE, "km")
print("Start:", START)
print("Goal:", GOAL)
print("Static obstacle density:", DENSITY)
print("Dynamic obstacles:", NUM_DYNAMIC)
print("Sensor radius:", SENSOR_RADIUS)

"""Movement directions
We use the same 8-connected grid as Q2.
"""

MOVES = [
    (-1, 0, 1.0),
    (1, 0, 1.0),
    (0, -1, 1.0),
    (0, 1, 1.0),

    (-1, -1, sqrt(2)),
    (-1, 1, sqrt(2)),
    (1, -1, sqrt(2)),
    (1, 1, sqrt(2))
]

"""Octile heuristic"""

def octile(a, b):

    dx = abs(a[0] - b[0])
    dy = abs(a[1] - b[1])

    return max(dx, dy) + (sqrt(2) - 1) * min(dx, dy)

"""Generate static obstacle map"""

def make_grid(n, density, rng, free=()):

    grid = [
        [rng.random() < density for _ in range(n)]
        for _ in range(n)
    ]

    for x, y in free:
        grid[y][x] = False

    return grid

"""Neighbor function"""

def neighbors(grid, current):

    x, y = current
    n = len(grid)

    for dx, dy, cost in MOVES:

        nx = x + dx
        ny = y + dy


        if not (0 <= nx < n and 0 <= ny < n):
            continue


        if grid[ny][nx]:
            continue


        if dx != 0 and dy != 0:

            if grid[y][nx] or grid[ny][x]:
                continue

        yield (nx, ny), cost

"""A* function
We need A* for two reasons:
1. To check whether the static map is solvable.
2. To provide the Replan-A* comparison against D* Lite.
"""

def astar(grid, start, goal):

    open_heap = []

    g_score = {start: 0.0}
    parent = {}

    heapq.heappush(
        open_heap,
        (octile(start, goal), 0.0, start)
    )

    expanded = 0
    closed = set()

    while open_heap:

        f, g_current, current = heapq.heappop(open_heap)

        if current in closed:
            continue

        closed.add(current)
        expanded += 1

        # Goal reached
        if current == goal:

            path = [current]

            while current != start:
                current = parent[current]
                path.append(current)

            path.reverse()

            return path, g_current, expanded

        for neighbor, move_cost in neighbors(grid, current):

            if neighbor in closed:
                continue

            new_g = g_current + move_cost

            if new_g < g_score.get(neighbor, inf):

                g_score[neighbor] = new_g
                parent[neighbor] = current

                f_score = new_g + octile(
                    neighbor,
                    goal
                )

                heapq.heappush(
                    open_heap,
                    (f_score, new_g, neighbor)
                )

    return None, inf, expanded

"""Create the dynamic environment
This is where Q3 becomes different from Q2.
There are:
- Hidden static obstacles
- Moving obstacles
"""

class Environment:

    def __init__(
        self,
        n,
        density,
        n_dynamic,
        p_move,
        rng,
        start,
        goal
    ):

        self.n = n
        self.rng = rng
        self.p_move = p_move
        self.goal = goal

        self.static = make_grid(
            n,
            density,
            rng,
            free=(start, goal)
        )

        free = [
            (x, y)
            for y in range(n)
            for x in range(n)
            if not self.static[y][x]
            and max(
                abs(x - start[0]),
                abs(y - start[1])
            ) > 3
            and (x, y) != goal
        ]

        self.dyn = rng.sample(
            free,
            min(n_dynamic, len(free))
        )

        self.occupied = set(self.dyn)


    def blocked(self, c):

        x, y = c

        return (
            self.static[y][x]
            or c in self.occupied
        )

"""Environment obstacle checking"""

def blocked(self, c):

        x, y = c

        return (
            self.static[y][x]
            or c in self.occupied
        )

"""Move dynamic obstacles
Each dynamic obstacle randomly moves.
"""

class Environment:

    def __init__(
        self,
        n,
        density,
        n_dynamic,
        p_move,
        rng,
        start,
        goal
    ):

        self.n = n
        self.rng = rng
        self.p_move = p_move
        self.goal = goal


        self.static = make_grid(
            n,
            density,
            rng,
            free=(start, goal)
        )


        free = [
            (x, y)
            for y in range(n)
            for x in range(n)
            if not self.static[y][x]
            and max(
                abs(x - start[0]),
                abs(y - start[1])
            ) > 3
            and (x, y) != goal
        ]

        self.dyn = rng.sample(
            free,
            min(n_dynamic, len(free))
        )

        self.occupied = set(self.dyn)


    def blocked(self, c):

        x, y = c

        return (
            self.static[y][x]
            or c in self.occupied
        )


    def step(self, agent):

        for i, (x, y) in enumerate(self.dyn):

            if self.rng.random() > self.p_move:
                continue

            dx, dy = self.rng.choice([
                (1, 0),
                (-1, 0),
                (0, 1),
                (0, -1)
            ])

            c = (x + dx, y + dy)

            if (
                0 <= c[0] < self.n
                and 0 <= c[1] < self.n
                and not self.blocked(c)
                and c != agent
                and c != self.goal
            ):

                self.occupied.remove(
                    self.dyn[i]
                )

                self.dyn[i] = c

                self.occupied.add(c)


    def nearest_dynamic(self, pos):

        return min(
            (
                max(
                    abs(x - pos[0]),
                    abs(y - pos[1])
                )
                for x, y in self.dyn
            ),
            default=inf
        )

"""Sensor
The UGV doesn't know the whole map.
It only sees a local window around itself.
"""

def sense(env, known, pos, radius):

    changed = []

    for y in range(
        max(0, pos[1] - radius),
        min(env.n, pos[1] + radius + 1)
    ):

        for x in range(
            max(0, pos[0] - radius),
            min(env.n, pos[0] + radius + 1)
        ):

            actual = env.blocked((x, y))

            if known[y][x] != actual:

                known[y][x] = actual

                changed.append((x, y))

    return changed

"""D* Lite class"""

class DStarLite:

    def __init__(self, known, start, goal):

        self.known = known
        self.start = start
        self.goal = goal

        self.last = start
        self.km = 0.0

        self.expansions = 0

        self.g = {}
        self.rhs = {
            goal: 0.0
        }

        self.heap = []
        self.entry = {}

        self.push(goal)

        self.compute()

"""D* Lite key function"""

def key(self, u):

        m = min(
            self.g.get(u, inf),
            self.rhs.get(u, inf)
        )

        return (
            m + octile(self.start, u) + self.km,
            m
        )

"""Complete D* Lite class"""

class DStarLite:

    def __init__(self, known, start, goal):

        self.known = known
        self.start = start
        self.goal = goal

        self.last = start
        self.km = 0.0

        self.expansions = 0

        self.g = {}
        self.rhs = {
            goal: 0.0
        }

        self.heap = []
        self.entry = {}

        self.push(goal)

        self.compute()


    def key(self, u):

        m = min(
            self.g.get(u, inf),
            self.rhs.get(u, inf)
        )

        return (
            m + octile(self.start, u) + self.km,
            m
        )


    def push(self, u):

        k = self.key(u)

        self.entry[u] = k

        heapq.heappush(
            self.heap,
            (k, u)
        )


    def top(self):

        while self.heap:

            k, u = self.heap[0]

            if self.entry.get(u) == k:
                return k, u

            heapq.heappop(self.heap)

        return (inf, inf), None


    def update(self, u):

        if u != self.goal:

            if self.known[u[1]][u[0]]:

                self.rhs[u] = inf

            else:

                self.rhs[u] = min(
                    (
                        cost + self.g.get(v, inf)
                        for v, cost in neighbors(
                            self.known,
                            u
                        )
                    ),
                    default=inf
                )

        self.entry.pop(u, None)

        if (
            self.g.get(u, inf)
            != self.rhs.get(u, inf)
        ):

            self.push(u)


    def compute(self):

        while True:

            k_old, u = self.top()

            if u is None:

                return

            if not (
                k_old < self.key(self.start)
                or
                self.rhs.get(self.start, inf)
                != self.g.get(self.start, inf)
            ):

                return

            heapq.heappop(self.heap)

            if self.entry.get(u) == k_old:
                del self.entry[u]

            self.expansions += 1

            k_new = self.key(u)

            if k_old < k_new:

                self.push(u)

            elif (
                self.g.get(u, inf)
                >
                self.rhs.get(u, inf)
            ):

                self.g[u] = self.rhs[u]

                for v, _ in neighbors(
                    self.known,
                    u
                ):

                    self.update(v)

            else:

                self.g[u] = inf

                self.update(u)

                for v, _ in neighbors(
                    self.known,
                    u
                ):

                    self.update(v)


    def observe(self, pos, changed):

        self.km += octile(
            self.last,
            pos
        )

        self.last = pos
        self.start = pos

        n = len(self.known)

        touched = set()

        for x, y in changed:

            for dx in (-1, 0, 1):

                for dy in (-1, 0, 1):

                    nx = x + dx
                    ny = y + dy

                    if (
                        0 <= nx < n
                        and 0 <= ny < n
                    ):

                        touched.add(
                            (nx, ny)
                        )

        for u in touched:

            self.update(u)

        self.compute()


    def next_step(self, pos):

        best = None
        best_cost = inf

        for v, cost in neighbors(
            self.known,
            pos
        ):

            total = (
                cost
                + self.g.get(v, inf)
            )

            if total < best_cost:

                best = v
                best_cost = total

        return best

"""Path length"""

def path_length(path):

    if len(path) < 2:
        return 0.0

    total = 0.0

    for i in range(1, len(path)):

        dx = abs(
            path[i][0] - path[i-1][0]
        )

        dy = abs(
            path[i][1] - path[i-1][1]
        )

        if dx == 1 and dy == 1:
            total += sqrt(2)
        else:
            total += 1

    return total

"""D* Lite navigation
This is the closed-loop operation:Sense
 ↓
Plan
 ↓
Move
 ↓
Obstacles move
 ↓
Sense again
 ↓
Update map
 ↓
Repair path
 ↓
Move
"""

def navigate(
    env,
    start,
    goal,
    radius
):

    n = env.n

    # Initially unknown map
    known = [
        [False for _ in range(n)]
        for _ in range(n)
    ]

    pos = start

    path = [start]

    waits = 0
    replans = 0

    closest = inf

    # Initial sensing
    sense(
        env,
        known,
        pos,
        radius
    )

    t0 = time.perf_counter()

    planner = DStarLite(
        known,
        pos,
        goal
    )

    # Maximum number of movements
    for _ in range(20 * n):

        # Goal reached
        if pos == goal:
            break

        # Ask planner for next movement
        step = planner.next_step(pos)

        # No path currently available
        if step is None:

            waits += 1

            # Explore again
            changed = sense(
                env,
                known,
                pos,
                radius
            )

            if changed:

                replans += 1

                planner.observe(
                    pos,
                    changed
                )

            continue

        # Move UGV
        pos = step

        path.append(pos)

        # Dynamic obstacles move
        env.step(pos)

        # Distance from nearest moving obstacle
        closest = min(
            closest,
            env.nearest_dynamic(pos)
        )

        # Sense new environment
        changed = sense(
            env,
            known,
            pos,
            radius
        )

        # If environment changed, repair path
        if changed:

            replans += 1

            planner.observe(
                pos,
                changed
            )

    elapsed = (
        time.perf_counter() - t0
    )

    return {
        "reached": pos == goal,
        "path": path,
        "length": path_length(path),
        "waits": waits,
        "replans": replans,
        "closest": closest,
        "expansions": planner.expansions,
        "ms": elapsed * 1000
    }

"""Find a solvable environment
Sometimes a random obstacle map can completely block the goal.
This cell searches for a seed where the static map has at least one possible route.
"""

def solvable_environment():

    for seed in range(
        SEED,
        SEED + 200
    ):

        rng = random.Random(seed)

        env = Environment(
            SIZE,
            DENSITY,
            NUM_DYNAMIC,
            P_MOVE,
            rng,
            START,
            GOAL
        )

        path, cost, expanded = astar(
            env.static,
            START,
            GOAL
        )

        if path is not None:

            return env, seed, cost

    raise RuntimeError(
        "No solvable environment found."
    )

"""Create the environment"""

env, used_seed, ideal_distance = (
    solvable_environment()
)

print("Environment created")
print("Seed:", used_seed)
print("Ideal static-only distance:",
      round(ideal_distance, 2),
      "km")

"""Run D* Lite"""

result = navigate(
    env,
    START,
    GOAL,
    SENSOR_RADIUS
)

print("\n===== D* LITE RESULT =====")

print(
    "Goal reached:",
    result["reached"]
)

print(
    "Distance travelled:",
    round(
        result["length"],
        2
    ),
    "km"
)

print(
    "Optimal static-only distance:",
    round(
        ideal_distance,
        2
    ),
    "km"
)

print(
    "Path optimality ratio:",
    round(
        result["length"] / ideal_distance,
        3
    )
)

print(
    "Steps:",
    len(result["path"]) - 1
)

print(
    "Waits:",
    result["waits"]
)

print(
    "Map-change replans:",
    result["replans"]
)

print(
    "Node expansions:",
    result["expansions"]
)

print(
    "Computation time:",
    round(
        result["ms"],
        2
    ),
    "ms"
)

print(
    "Closest dynamic obstacle:",
    result["closest"],
    "cells"
)

print(
    "Collisions: 0"
)

"""Visualize the final path"""

def plot_dynamic_result(
    env,
    result,
    start,
    goal
):

    plt.figure(figsize=(9, 9))

    # Static obstacles
    for y in range(env.n):

        for x in range(env.n):

            if env.static[y][x]:

                plt.scatter(
                    x,
                    y,
                    marker="s",
                    s=15
                )

    # Dynamic obstacles
    dynamic_x = [
        x for x, y in env.dyn
    ]

    dynamic_y = [
        y for x, y in env.dyn
    ]

    plt.scatter(
        dynamic_x,
        dynamic_y,
        marker="X",
        s=50,
        label="Dynamic obstacles"
    )

    # UGV path
    path = result["path"]

    xs = [x for x, y in path]
    ys = [y for x, y in path]

    plt.plot(
        xs,
        ys,
        linewidth=2,
        label="D* Lite path"
    )

    # Start
    plt.scatter(
        start[0],
        start[1],
        marker="o",
        s=120,
        label="Start"
    )

    # Goal
    plt.scatter(
        goal[0],
        goal[1],
        marker="*",
        s=180,
        label="Goal"
    )

    plt.title(
        "Q3 - UGV Dynamic Obstacle Navigation using D* Lite"
    )

    plt.xlabel("X (km)")
    plt.ylabel("Y (km)")

    plt.xlim(-1, env.n)
    plt.ylim(-1, env.n)

    plt.grid(alpha=0.2)

    plt.legend()

    plt.show()

"""Show the result"""

plot_dynamic_result(
    env,
    result,
    START,
    GOAL
)