# -*- coding: utf-8 -*-
"""AI_assignment_Q2_uav.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lkJnKqc0gOt_Dl4Qx5PQhr2nFuY9ouk

2. An Unmanned Ground Vehicle (UGV) is a robot that finds the optimal path from a given user
specified start node to a user-specified Goal node on a map of a small area in a battlefield (Eg
70x70 Kms). There are obstacles known a-priori. The density of the obstacles can be
generated randomly with three different levels of density. Design an algorithm that makes
the UGV to navigate through this grid space avoiding all the known obstacles to reach the
goal by the shortest distance. Trace this path along with the Measures of Effectiveness.

Import libraries
"""

import random
import time
import heapq
from math import inf, hypot, sqrt
import matplotlib.pyplot as plt

"""Set the problem parameters"""

SIZE = 70


START = (0, 0)
GOAL = (69, 69)


SEED = 7

DENSITY_LEVELS = {
    "low": 0.15,
    "medium": 0.25,
    "high": 0.35
}

print("Grid size:", SIZE, "x", SIZE, "km")
print("Start:", START)
print("Goal:", GOAL)
print("Obstacle densities:", DENSITY_LEVELS)

"""Create the battlefield grid"""

def make_grid(n, density, rng, free=()):
    """
    Create an n x n grid.

    False = free cell
    True  = obstacle
    """

    grid = [
        [rng.random() < density for _ in range(n)]
        for _ in range(n)
    ]


    for x, y in free:
        grid[y][x] = False

    return grid

"""Define 8 possible movements
The UGV can move:
- Up
- Down
- Left
- Right
- 4 diagonal directions
"""

MOVES = [
    (-1, 0, 1.0),
    (1, 0, 1.0),
    (0, -1, 1.0),
    (0, 1, 1.0),

    (-1, -1, sqrt(2)),
    (-1, 1, sqrt(2)),
    (1, -1, sqrt(2)),
    (1, 1, sqrt(2))
]

"""Neighbor function"""

def neighbors(grid, current):
    x, y = current
    n = len(grid)

    for dx, dy, cost in MOVES:

        nx = x + dx
        ny = y + dy


        if not (0 <= nx < n and 0 <= ny < n):
            continue

        if grid[ny][nx]:
            continue

        if dx != 0 and dy != 0:

            if grid[y][nx] or grid[ny][x]:
                continue

        yield (nx, ny), cost

"""Octile heuristic
Because we are using an 8-connected grid, the octile distance is appropriate.
"""

def octile(a, b):
    dx = abs(a[0] - b[0])
    dy = abs(a[1] - b[1])

    return max(dx, dy) + (sqrt(2) - 1) * min(dx, dy)

"""A* algorithm"""

def astar(grid, start, goal):

    open_heap = []

    g_score = {start: 0.0}


    parent = {}

    heapq.heappush(
        open_heap,
        (octile(start, goal), 0.0, start)
    )

    expanded = 0
    closed = set()

    while open_heap:

        f, g_current, current = heapq.heappop(open_heap)


        if current in closed:
            continue

        closed.add(current)
        expanded += 1


        if current == goal:

            path = [current]

            while current != start:
                current = parent[current]
                path.append(current)

            path.reverse()

            return path, g_current, expanded

        for neighbor, move_cost in neighbors(grid, current):

            if neighbor in closed:
                continue

            new_g = g_current + move_cost

            if new_g < g_score.get(neighbor, inf):

                g_score[neighbor] = new_g
                parent[neighbor] = current

                f_score = new_g + octile(neighbor, goal)

                heapq.heappush(
                    open_heap,
                    (f_score, new_g, neighbor)
                )

    return None, inf, expanded

"""Calculate path length"""

def path_length(path):

    if path is None or len(path) < 2:
        return 0.0

    total = 0.0

    for i in range(1, len(path)):

        x1, y1 = path[i - 1]
        x2, y2 = path[i]

        dx = abs(x2 - x1)
        dy = abs(y2 - y1)

        if dx == 1 and dy == 1:
            total += sqrt(2)
        else:
            total += 1.0

    return total

"""Count turns"""

def count_turns(path):

    if path is None or len(path) < 3:
        return 0

    turns = 0

    previous_direction = None

    for i in range(1, len(path)):

        dx = path[i][0] - path[i-1][0]
        dy = path[i][1] - path[i-1][1]

        direction = (dx, dy)

        if previous_direction is not None:
            if direction != previous_direction:
                turns += 1

        previous_direction = direction

    return turns

"""Calculate obstacle clearance
This tells us how close the UGV gets to obstacles.
"""

def clearance_map(grid):

    n = len(grid)

    result = [[inf for _ in range(n)] for _ in range(n)]

    obstacles = []

    for y in range(n):
        for x in range(n):
            if grid[y][x]:
                obstacles.append((x, y))

    if not obstacles:
        return result

    for y in range(n):
        for x in range(n):

            if grid[y][x]:
                result[y][x] = 0
                continue

            minimum = inf

            for ox, oy in obstacles:

                distance = hypot(x - ox, y - oy)

                minimum = min(minimum, distance)

            result[y][x] = minimum

    return result

"""Measures of Effectiveness"""

def measures_of_effectiveness(
    grid,
    path,
    start,
    goal,
    expanded,
    seconds
):

    clear = clearance_map(grid)

    clearances = [
        clear[y][x]
        for x, y in path
    ]

    straight = hypot(
        goal[0] - start[0],
        goal[1] - start[1]
    )

    length = path_length(path)

    n = len(grid)

    return {
        "Path length (km)": round(length, 2),

        "Straight-line distance (km)": round(
            straight, 2
        ),

        "Detour factor": round(
            length / straight, 3
        ) if straight else 1.0,

        "Nodes expanded": expanded,

        "Search space used (%)": round(
            100 * expanded / (n * n), 2
        ),

        "Planning time (ms)": round(
            seconds * 1000, 2
        ),

        "Waypoints": len(path),

        "Turns": count_turns(path),

        "Minimum clearance (km)": round(
            min(clearances), 2
        ),

        "Mean clearance (km)": round(
            sum(clearances) / len(clearances), 2
        )
    }

"""Visualize the grid and path"""

def plot_grid(grid, path, start, goal, title):

    n = len(grid)

    plt.figure(figsize=(8, 8))

    # Obstacles
    for y in range(n):
        for x in range(n):

            if grid[y][x]:
                plt.scatter(
                    x,
                    y,
                    marker="s",
                    s=15
                )

    # Path
    if path:

        xs = [p[0] for p in path]
        ys = [p[1] for p in path]

        plt.plot(
            xs,
            ys,
            linewidth=2,
            label="A* Path"
        )

    # Start
    plt.scatter(
        start[0],
        start[1],
        marker="o",
        s=100,
        label="Start"
    )

    # Goal
    plt.scatter(
        goal[0],
        goal[1],
        marker="*",
        s=150,
        label="Goal"
    )

    plt.title(title)

    plt.xlabel("X (km)")
    plt.ylabel("Y (km)")

    plt.xlim(-1, n)
    plt.ylim(-1, n)

    plt.grid(alpha=0.2)

    plt.legend()

    plt.show()

"""Run Q2 for ONE density first"""

level = "low"

rng = random.Random(f"{SEED}-{level}")

grid = make_grid(
    SIZE,
    DENSITY_LEVELS[level],
    rng,
    free=(START, GOAL)
)

t0 = time.perf_counter()

path, cost, expanded = astar(
    grid,
    START,
    GOAL
)

elapsed = time.perf_counter() - t0

print("Density:", level)
print("Path found:", path is not None)
print("Nodes expanded:", expanded)
print("Planning time:", round(elapsed * 1000, 2), "ms")

if path:
    print("Path length:", round(path_length(path), 2), "km")

"""Print MoE for low density"""

if path:

    moe = measures_of_effectiveness(
        grid,
        path,
        START,
        GOAL,
        expanded,
        elapsed
    )

    print("\n=== LOW DENSITY MoE ===")

    for key, value in moe.items():
        print(f"{key:<30}: {value}")

"""Display the traced path"""

if path:

    plot_grid(
        grid,
        path,
        START,
        GOAL,
        "Q2 - A* UGV Path - LOW Density"
    )

"""Run ALL THREE densities"""

results = {}

for level, density in DENSITY_LEVELS.items():

    print("\n" + "=" * 60)
    print(
        f"{level.upper()} DENSITY "
        f"(target = {density * 100:.0f}%)"
    )
    print("=" * 60)

    rng = random.Random(f"{SEED}-{level}")

    grid = make_grid(
        SIZE,
        density,
        rng,
        free=(START, GOAL)
    )

    actual_density = (
        100 * sum(map(sum, grid)) / (SIZE * SIZE)
    )

    t0 = time.perf_counter()

    path, cost, expanded = astar(
        grid,
        START,
        GOAL
    )

    elapsed = time.perf_counter() - t0

    print(
        f"Actual obstacle density: "
        f"{actual_density:.1f}%"
    )

    if path is None:

        print(
            f"No feasible path. "
            f"{expanded} nodes expanded."
        )

        results[level] = None

        continue

    moe = measures_of_effectiveness(
        grid,
        path,
        START,
        GOAL,
        expanded,
        elapsed
    )

    results[level] = {
        "grid": grid,
        "path": path,
        "cost": cost,
        "moe": moe
    }

    for key, value in moe.items():
        print(f"{key:<30}: {value}")

"""Plot all three paths"""

for level in DENSITY_LEVELS:

    if results[level] is not None:

        plot_grid(
            results[level]["grid"],
            results[level]["path"],
            START,
            GOAL,
            f"Q2 - A* Path - {level.upper()} Density"
        )

"""Final comparison table"""

print("\n" + "=" * 90)
print("Q2 FINAL COMPARISON")
print("=" * 90)

print(
    f"{'Density':<12}"
    f"{'Path(km)':<12}"
    f"{'Expanded':<12}"
    f"{'Time(ms)':<12}"
    f"{'Turns':<10}"
    f"{'Detour':<10}"
)

print("-" * 90)

for level in DENSITY_LEVELS:

    if results[level] is None:

        print(f"{level:<12} No feasible path")

        continue

    m = results[level]["moe"]

    print(
        f"{level:<12}"
        f"{m['Path length (km)']:<12}"
        f"{m['Nodes expanded']:<12}"
        f"{m['Planning time (ms)']:<12}"
        f"{m['Turns']:<10}"
        f"{m['Detour factor']:<10}"
    )

"""I model the battlefield as a 70×70 grid and use A* with an octile heuristic to find the optimal shortest collision-free path through known static obstacles at low, medium and high obstacle densities."""

